# Generated by Django 4.1.2 on 2022-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fixedasset_stock_number'),
        ('people', '0004_worker_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_fixed_asset',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.fixedasset', verbose_name='Fixed Asset'),
        ),
    ]
