# Generated by Django 4.1.2 on 2022-12-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_fixedasset_model_alter_fixedasset_stock_number'),
        ('people', '0005_alter_worker_id_fixed_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_fixed_asset',
            field=models.ManyToManyField(to='inventory.fixedasset', verbose_name='Fixed Asset'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
