# Generated by Django 4.1.2 on 2022-12-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_worker_id_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id_fixed_asset',
        ),
    ]
