# Generated by Django 4.1.2 on 2023-03-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headdepartment',
            name='id_department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.department', verbose_name='Departamentos   '),
        ),
        migrations.AlterField(
            model_name='headdepartment',
            name='id_worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.worker', verbose_name='Trabajador'),
        ),
    ]
