# Generated by Django 4.1.2 on 2023-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_headdepartment_id_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id_area',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Nombre del Área'),
        ),
    ]
