# Generated by Django 4.1.2 on 2023-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_department_id_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id_area',
            field=models.PositiveIntegerField(null=True, verbose_name='Nombre del Área'),
        ),
    ]
