# Generated by Django 4.1.2 on 2022-11-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetStatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(max_length=1, unique=True, verbose_name='Statu')),
            ],
            options={
                'verbose_name': 'Fixed Asset Statu',
                'verbose_name_plural': 'Fixed Assets Status',
            },
        ),
        migrations.CreateModel(
            name='FixedAssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_FixedAsset', models.CharField(max_length=100, unique=True, verbose_name='Fixed Asset Type')),
            ],
            options={
                'verbose_name': 'Fixed Asset Type',
                'verbose_name_plural': 'Fixed Assets Types',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(null=True, unique=True, verbose_name='Office number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Stock number')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serial number')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('id_fixed_asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fixedassettype', verbose_name='Fixed Asset Type')),
                ('id_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.office', verbose_name='Office')),
                ('id_statu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fixedassetstatu', verbose_name='Statu')),
            ],
            options={
                'verbose_name': 'Fixed Assets',
                'verbose_name_plural': 'Fixed Assets',
                'permissions': (('can_view_all_fixedasset', 'Can view all Fixed Asset'), ('can_view_the_dpto_fixedasset', 'Can view the dpto Fixed Asset')),
            },
        ),
    ]
