# Generated by Django 4.1.2 on 2022-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='stock_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Stock number'),
        ),
    ]
