# Generated by Django 4.1.2 on 2022-12-12 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_fixedasset_stock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='stock_number',
            field=models.CharField(help_text='[6-10]', max_length=10, unique=True, validators=[django.core.validators.MinValueValidator(6, 'Debe ser mayor que 6 digitos'), django.core.validators.MaxValueValidator(10, 'Debe ser menor que 10 digitos')], verbose_name='Stock number'),
        ),
    ]
