# Generated by Django 4.1.2 on 2022-12-13 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_fixedasset_stock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='model',
            field=models.CharField(blank=True, help_text='[A-Z, 0-8, -]', max_length=25, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='stock_number',
            field=models.CharField(help_text='[6-10, A-Z]', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Debe ser mayor que 6 digitos'), django.core.validators.MaxLengthValidator(10, 'Debe ser menor que 10 digitos')], verbose_name='Stock number'),
        ),
    ]
