# Generated by Django 4.1.2 on 2022-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_worker_id_fixed_asset'),
        ('inventory', '0004_alter_fixedasset_model_alter_fixedasset_stock_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='id_worker',
            field=models.ManyToManyField(to='people.worker', verbose_name='Worker'),
        ),
    ]
