# Generated by Django 4.1.2 on 2023-01-19 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_fixedasset_id_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='stock_number',
            field=models.CharField(help_text='[6-10]', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Debe ser mayor que 6 digitos'), django.core.validators.MaxLengthValidator(10, 'Debe ser menor que 10 digitos')], verbose_name='Stock number'),
        ),
    ]
