# Generated by Django 4.1.2 on 2023-02-02 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_department_options_alter_headarea_options_and_more'),
        ('inventory', '0006_alter_fixedasset_stock_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedasset',
            options={'permissions': (('can_view_all_fixedasset', 'Can view all Fixed Asset'), ('can_view_the_dpto_fixedasset', 'Can view the dpto Fixed Asset')), 'verbose_name': 'Activo Fijo', 'verbose_name_plural': 'Activos Fijos'},
        ),
        migrations.AlterModelOptions(
            name='fixedassetstatu',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='fixedassettype',
            options={'verbose_name': 'Tipo de Activo Fijo', 'verbose_name_plural': 'Tipos de Activos Fijos'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='id_fixed_asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fixedassettype', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='id_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.office', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='id_statu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fixedassetstatu', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='id_worker',
            field=models.ManyToManyField(blank=True, null=True, to='people.worker', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Uso'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='Ultima actualización'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='model',
            field=models.CharField(blank=True, help_text='[A-Z, 0-8, -]', max_length=25, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='stock_number',
            field=models.CharField(help_text='[6-10]', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Debe ser mayor que 6 digitos'), django.core.validators.MaxLengthValidator(10, 'Debe ser menor que 10 digitos')], verbose_name='Número de inventario'),
        ),
        migrations.AlterField(
            model_name='fixedassetstatu',
            name='statu',
            field=models.CharField(max_length=1, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fixedassettype',
            name='type_FixedAsset',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Número de Oficina'),
        ),
    ]
