# Generated by Django 4.1.2 on 2023-02-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_department_options_alter_headarea_options_and_more'),
        ('inventory', '0008_alter_fixedasset_id_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='id_worker',
            field=models.ManyToManyField(blank=True, null=True, to='people.worker', verbose_name='Trabajador'),
        ),
    ]
