# Generated by Django 4.1.2 on 2023-02-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_fixedasset_id_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='id_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.office', verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='En uso'),
        ),
    ]
