# Generated by Django 4.1.2 on 2023-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_fixedasset_id_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(blank=True, help_text='Nombre o número descriptivo de la oficina', max_length=30, null=True, unique=True, verbose_name='Nombre de Oficina'),
        ),
    ]
