# Generated by Django 4.1.2 on 2023-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(help_text='[Nombre o número descriptivo de la oficina]', max_length=30, null=True, unique=True, verbose_name='Nombre de Oficina'),
        ),
    ]
