# Generated by Django 4.1.2 on 2023-03-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_office_description_alter_office_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='id_area',
            field=models.PositiveIntegerField(null=True, verbose_name='Área'),
        ),
    ]
